name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO: Include 22 and 23 when https://github.com/yeoman/yeoman-welcome/issues/7 is fixed
        node: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
        exclude:
          # Avoid Error: Unable to find Node versions for platform darwin and architecture arm64: 
          # @SEE: https://github.com/yeoman/yeoman-welcome/actions/runs/12846318454/job/35821411749?pr=6
          - os: macos-latest
            node: 8
          - os: macos-latest
            node: 9
          - os: macos-latest
            node: 10
          - os: macos-latest
            node: 11
          - os: macos-latest
            node: 12
          - os: macos-latest
            node: 13
          - os: macos-latest
            node: 14
          - os: macos-latest
            node: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test